type: class
include_relations_also_as_members: false
glob:
  - src/config/config.cc
include:
  namespaces:
    - clanguml::config
using_namespace:
  - clanguml::config
plantuml:
  before:
    - 'title clang-uml configuration model'